import = [
  "~/.config/alacritty/themes/themes/atom_one_light.toml"
]

[env]
TERM = "screen-256color"

[window]
option_as_alt = "OnlyLeft"

[font]
size = 16.0
normal = { family = "Hack", style = "Regular" }
bold = { family = "Hack", style = "Bold" }
italic = { family = "Hack", style = "Italic" }
