# === Font Configuration === #
font:
  normal:
    family: Hack
    style: Regular
  bold:
    family: Hack
    style: Bold
  italic:
    family: Hack
    style: Italic
  size: 16.0

# == Key Bindings === #
key_bindings:
  - { key: Comma,     mods: Command,      command:
      {program: "open", args: ["~/.config/alacritty/alacritty.yml"]}     }
  - { key: N,         mods: Command,      action: SpawnNewInstance       }
  - { key: Space,     mods: Alt,          chars: " "                     }
  - { key: B, mods: Alt, chars: "\x1bb" }
  - { key: F, mods: Alt, chars: "\x1bf" }

colors:
  # Default colors
  primary:
    background: '0x000000'

  normal:
    black: '0x000000'
