import = [
  "~/.config/alacritty/themes/themes/github_light.toml"
]

[window]
option_as_alt = "OnlyLeft"

[font]
size = 18.0
normal = { family = "Hack", style = "Regular" }
bold = { family = "Hack", style = "Bold" }
italic = { family = "Hack", style = "Italic" }
